version: '3.0'

services:
  web:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes: 
      - .:/etc/letsencrypt/archive/
      - .:/etc/letsencrypt/live/
    command: nginx -g 'daemon off;'
